#############################################################################
# Makefile for building: Simulateur
# Generated by qmake (2.01a) (Qt 4.8.7) on: lun. janv. 6 21:21:52 2020
# Project:  Simulateur.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Simulateur.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -IProjetC++ -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aff.cc \
		exercice.cc \
		main.cc \
		ProjetC++/Moteur.cc \
		ProjetC++/Pompe.cc \
		ProjetC++/Systeme.cc \
		ProjetC++/Tank.cc \
		ProjetC++/VanneMoteur.cc \
		ProjetC++/VanneTank.cc moc_aff.cpp \
		moc_exercice.cpp \
		moc_Systeme.cpp
OBJECTS       = aff.o \
		exercice.o \
		main.o \
		Moteur.o \
		Pompe.o \
		Systeme.o \
		Tank.o \
		VanneMoteur.o \
		VanneTank.o \
		moc_aff.o \
		moc_exercice.o \
		moc_Systeme.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Simulateur.pro
QMAKE_TARGET  = Simulateur
DESTDIR       = 
TARGET        = Simulateur

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Simulateur.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Simulateur.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Simulateur.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Simulateur1.0.0 || $(MKDIR) .tmp/Simulateur1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Simulateur1.0.0/ && $(COPY_FILE) --parents aff.hh exercice.hh ProjetC++/Moteur.hh ProjetC++/Pompe.hh ProjetC++/Systeme.hh ProjetC++/Tank.hh ProjetC++/VanneMoteur.hh ProjetC++/VanneTank.hh .tmp/Simulateur1.0.0/ && $(COPY_FILE) --parents aff.cc exercice.cc main.cc ProjetC++/Moteur.cc ProjetC++/Pompe.cc ProjetC++/Systeme.cc ProjetC++/Tank.cc ProjetC++/VanneMoteur.cc ProjetC++/VanneTank.cc .tmp/Simulateur1.0.0/ && (cd `dirname .tmp/Simulateur1.0.0` && $(TAR) Simulateur1.0.0.tar Simulateur1.0.0 && $(COMPRESS) Simulateur1.0.0.tar) && $(MOVE) `dirname .tmp/Simulateur1.0.0`/Simulateur1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Simulateur1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aff.cpp moc_exercice.cpp moc_Systeme.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aff.cpp moc_exercice.cpp moc_Systeme.cpp
moc_aff.cpp: aff.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) aff.hh -o moc_aff.cpp

moc_exercice.cpp: aff.hh \
		ProjetC++/Systeme.hh \
		ProjetC++/Pompe.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Moteur.hh \
		ProjetC++/VanneMoteur.hh \
		ProjetC++/VanneTank.hh \
		exercice.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) exercice.hh -o moc_exercice.cpp

moc_Systeme.cpp: ProjetC++/Pompe.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Moteur.hh \
		ProjetC++/VanneMoteur.hh \
		ProjetC++/VanneTank.hh \
		ProjetC++/Systeme.hh
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) ProjetC++/Systeme.hh -o moc_Systeme.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

aff.o: aff.cc aff.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aff.o aff.cc

exercice.o: exercice.cc exercice.hh \
		aff.hh \
		ProjetC++/Systeme.hh \
		ProjetC++/Pompe.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Moteur.hh \
		ProjetC++/VanneMoteur.hh \
		ProjetC++/VanneTank.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exercice.o exercice.cc

main.o: main.cc aff.hh \
		ProjetC++/Systeme.hh \
		ProjetC++/Pompe.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Moteur.hh \
		ProjetC++/VanneMoteur.hh \
		ProjetC++/VanneTank.hh \
		exercice.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

Moteur.o: ProjetC++/Moteur.cc ProjetC++/Moteur.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Pompe.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Moteur.o ProjetC++/Moteur.cc

Pompe.o: ProjetC++/Pompe.cc ProjetC++/Pompe.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pompe.o ProjetC++/Pompe.cc

Systeme.o: ProjetC++/Systeme.cc ProjetC++/Systeme.hh \
		ProjetC++/Pompe.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Moteur.hh \
		ProjetC++/VanneMoteur.hh \
		ProjetC++/VanneTank.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Systeme.o ProjetC++/Systeme.cc

Tank.o: ProjetC++/Tank.cc ProjetC++/Tank.hh \
		ProjetC++/Pompe.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tank.o ProjetC++/Tank.cc

VanneMoteur.o: ProjetC++/VanneMoteur.cc ProjetC++/VanneMoteur.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Pompe.hh \
		ProjetC++/Moteur.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VanneMoteur.o ProjetC++/VanneMoteur.cc

VanneTank.o: ProjetC++/VanneTank.cc ProjetC++/VanneTank.hh \
		ProjetC++/Tank.hh \
		ProjetC++/Pompe.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VanneTank.o ProjetC++/VanneTank.cc

moc_aff.o: moc_aff.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aff.o moc_aff.cpp

moc_exercice.o: moc_exercice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exercice.o moc_exercice.cpp

moc_Systeme.o: moc_Systeme.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Systeme.o moc_Systeme.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

